name: Redbus Price Tracker

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (in UTC)
  workflow_dispatch:       # Manual trigger if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Debug - Check env vars (do not print actual values!)
        run: |
          echo "BOT token starts with: ${TELEGRAM_BOT_TOKEN:0:5}"
          echo "Chat ID length: ${#TELEGRAM_CHAT_ID}"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      - name: Build and Run Tests
        run: mvn clean test

      - name: Upload Debug Screenshot
        if: always()  # ensures it uploads even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: redbus-debug-screenshots
          path: screenshots/