name: Redbus Price Tracker

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours (in UTC)
  workflow_dispatch:       # Manual trigger if needed

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Debug - Check env vars (do not print actual values!)
        run: |
          echo "BOT token starts with: ${TELEGRAM_BOT_TOKEN:0:5}"
          echo "Chat ID length: ${#TELEGRAM_CHAT_ID}"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Run
        run: mvn clean test
